version: '2'
services:
    ajax:
        image: ajax
        ports:
            - "5000:5000"
        entrypoint: ./script.sh

    data:
        restart: always
        image: mysql:5.6
        volumes:
            - /var/lib/mysql
        command: "true"

    db:
        restart: always
        image: mysql:5.6
        volumes:
            - ./mysql_conf:/etc/mysql/conf.d
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: db_harsh
        tty: true
